% Machine Learnign Exercise 2
% Problem 2(a)
% Po-Hsuan Huang 2014.11.7



% Load the variables in the file Homework2.mat. 
% Assuming that these data are generated by a Poisson distribution with 
% parameter theda, and using a Gamma-distribution with parameters alpha= 2 and beta = 1,
% calculate and plot the posterior distribution over theda. 
% [You do not need the statistics toolbox, 
% but if you use the function gampdf in it , 
% please note that it uses a different parameterization of the 
% gamma distribution.]

function ML_HW2_1_PoHsuan_Huang(alpha,beta,data)

% plot the prior distribution, which is x in the given file Homework2.mat.

 summation= sum(data);
 length = size(data,2);
 prior = gamma_dist(alpha,beta);
 posterior = gamma_dist(alpha+summation,beta+length);
 
 figure(1)
 plot( posterior(1,:), posterior(2,:));
 hold on
 plot( prior(1,:),prior(2,:));
 title('posterior probability distribution over theda' );
 xlabel('theda');
 ylabel('probability');
 legend( 'posterior', 'prior');
 hold off

end

%Gamma distribution

function [value]= gamma_dist(a,b)
 theda = 0:0.01:10;
 value(1,:) = theda;
 value(2,:) = ( b^a/gamma(a) )* (theda.^(a-1)) .* exp(-b*theda) ;
 
 
end







